query SearchCollections($searchTerm: String, $topSupply: Boolean, $size: Int) {
  searchCollections(
    searchTerm: $searchTerm
    topSupply: $topSupply
    size: $size
  ) {
    name
    address
    total_supply
  }
}
